#ifndef LSIM_LSIMTYPES_H
#define LSIM_LSIMTYPES_H
#include <deque>

#define LSIM_CHECK(func) do {\
	if (const auto err = func; err)\
		return err;\
	} while (0)

namespace LSIM {
	enum class ErrorCode {
		WINDOW_CREATION_FAILURE,
		VK_INSTANCE_CREATION_FAILURE,
		GLFW_GET_EXTENSIONS_FAILURE,
		VK_VALIDATION_LAYERS_MISSING,
		VK_DEBUG_MESSENGER_FUNCTION_POINTER_MISSING,
		VK_DEBUG_MESSENGER_CREATION_FAILURE,
		VK_SURFACE_CREATION_FAILURE,
		VK_ENUMERATE_PHYSICAL_DEVICES_FAILURE,
		VK_GET_PHYSICAL_DEVICE_SURFACE_SUPPORT_FAILURE,
		VK_NO_SUITABLE_DEVICE_FOUND,
		VK_DEVICE_CREATION_FAILURE,
		VK_GET_PHYSICAL_DEVICE_SURFACE_CAPABILITIES_FAILURE,
		VK_GET_PHYSICAL_DEVICE_SURFACE_FORMATS_FAILURE,
		VK_GET_PHYSICAL_DEVICE_SURFACE_PRESENT_MODES_FAILURE,
		VK_NO_SURFACE_FORMATS,
		VK_CREATE_SWAPCHAIN_FAILURE,
		VK_FRAMEBUFFER_ZERO_SIZE,
		VK_GET_SWAPCHAIN_IMAGES_FAILURE,
		VK_CREATE_IMAGE_VIEW_FAILURE,
		VK_CREATE_RENDER_PASS_FAILURE,
		VK_CREATE_FRAMEBUFFER_FAILURE,
		VK_CREATE_SHADER_MODULE_FAILURE,
		VK_CREATE_PIPELINE_LAYOUT_FAILURE,
		VK_CREATE_GRAPHICS_PIPELINES_FAILURE,
		VK_CREATE_COMMAND_POOL_FAILURE,
		VK_ALLOCATE_COMMAND_BUFFERS_FAILURE,
		VK_CREATE_SEMAPHORE_FAILURE,
		VK_CREATE_FENCE_FAILURE,
		VK_CREATE_IMAGE_FAILURE,
		VK_NO_VALID_DEPTH_BUFFER_FORMAT,
		VK_NO_VALID_MEMORY_TYPE,
		VK_MEMORY_ALLOCATION_FAILURE,
		VK_CREATE_BUFFER_FAILURE,
		VK_BIND_BUFFER_FAILURE,
		VK_MEMORY_MAP_FAILURE,
		VK_BEGIN_COMMAND_BUFFER_FAILURE,
		VK_END_COMMAND_BUFFER_FAILURE,
		VK_QUEUE_SUBMIT_FAILURE,
		VK_WAIT_FOR_FENCE_FAILURE,
		VK_CREATE_DESCRIPTOR_SET_LAYOUT_FAILURE,
		VK_CREATE_DESCRIPTOR_POOL_FAILURE,
		VK_ALLOCATE_DESCRIPTOR_SETS_FAILURE,
	};

	enum class FatalityLevel {
		FATAL,
		ERROR,
		WARNING
	};

	struct Error {
		ErrorCode code;
		FatalityLevel fatality;
	};

	template <typename T>
	struct CapacityBuffer {
		std::deque<T> buffer;
		unsigned int capacity = 1;
		void push_back(const T& value) {
			if (buffer.size() == capacity) buffer.pop_front();
			buffer.push_back(value);
		}
		void push_back(T&& value) {
			if (buffer.size() == capacity) buffer.pop_front();
			buffer.push_back(std::move(value));
		}
		explicit CapacityBuffer(const unsigned int c) : capacity(c){}
	};
}

#endif //LSIM_LSIMTYPES_H
